#https://www.mkdocs.org/user-guide/configuration/#
site_name: HEAL Platform Documentation
site_url: https://heal-docs-dev.io
repo_url: 
nav:
  - Home: index.md
  - Types of Hosted Data: hosted_data_types.md
  - Data Management and Repositories: data_mgmt_and_repos.md
  - HEAL Platform Quick Start:
    - Overview: platform_overview.md
    - Login Page: platform_login.md
    - Access check/request: platform_request_access.md
    - Discovery Page: platform_discovery_page.md
    - Workspaces: platform_workspaces.md
    - Example Analysis Page: platform_example_analyses.md
    - Profile Page: platform_profile_page.md
  - Tutorial Videos: platform_tutorial_videos.md
  - Data File Downloads: downloading_files.md
  - FAQs: faqs.md
  - Contact: contact.md
# extra_css:
#   - css/healdata_org2.css
theme:
  name: mkdocs
  # custom_dir: custom_theme/
use_directory_urls: true
markdown_extensions:
    - toc:
        permalink: "###"
plugins:
  - search
  # - mkdocs-video: 
  #     is_video: True 
  #- mermaid2
  #- offline


# TODO: add footer (this may be included in the custom jinja template?)
#    [![](img/gen3.png)](https://ctds.uchicago.edu/gen3)[![](img/createdby.png)](https://ctds.uchicago.edu/)
#   [![image alt text](image URL link)](anchor link)

# function readMore() { var dots = document.getElementById("dots"); var moreText = document.getElementById("more"); var btnText = document.getElementById("read-more-btn"); var btnText = document.getElementById("read-more-explorer"); if (dots.style.display === "none") { dots.style.display = "inline"; btnText.innerHTML = "Read more"; moreText.style.display = "none"; } else { dots.style.display = "none"; btnText.innerHTML = "Read less"; moreText.style.display = "inline"; } }